# panda:
  # Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50 

# # Position Controllers ---------------------------------------
panda_arm_controller:
  type: "effort_controllers/JointGroupPositionController"
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7
  panda_joint1:   
    pid: {p: 100.0, i: 0.0, d: 10, i_clamp: 0.0}
  panda_joint2:   
    pid: {p: 100.0, i: 0.0, d: 10, i_clamp: 0.0}
  panda_joint3:   
    pid: {p: 100.0, i: 0.0, d: 10, i_clamp: 0.0}
  panda_joint4:   
    pid: {p: 100.0, i: 0.0, d: 10, i_clamp: 0.0}
  panda_joint5:   
    pid: {p: 100.0, i: 0.0, d: 10, i_clamp: 0.0}
  panda_joint6:   
    pid: {p: 100.0, i: 0.0, d: 10, i_clamp: 0.0}
  panda_joint7:   
    pid: {p: 100.0, i: 0.0, d: 10, i_clamp: 0.0}

panda_gripper_controller:
  type: "effort_controllers/JointGroupPositionController"
  joints:
    - panda_finger_joint1
    - panda_finger_joint2
  panda_finger_joint1:   
    pid: {p: 100.0, i: 0.0, d: 10, i_clamp: 0.0}
  panda_finger_joint2:   
    pid: {p: 100.0, i: 0.0, d: 10, i_clamp: 0.0}

# joint1_position_controller:
#   type: effort_controllers/JointPositionController
#   joint: panda_joint1
#   pid: {p: 100.0, i: 0.01, d: 10.0}
# joint2_position_controller:
#   type: effort_controllers/JointPositionController
#   joint: panda_joint2
#   pid: {p: 100.0, i: 0.01, d: 10.0}

# joint3_position_controller:
#   type: effort_controllers/JointPositionController
#   joint: panda_joint3
#   pid: {p: 100.0, i: 0.01, d: 10.0}
# joint4_position_controller:
#   type: effort_controllers/JointPositionController
#   joint: panda_joint4
#   pid: {p: 100.0, i: 0.01, d: 10.0}

# joint5_position_controller:
#   type: effort_controllers/JointPositionController
#   joint: panda_joint5
#   pid: {p: 100.0, i: 0.01, d: 10.0}
# joint6_position_controller:
#   type: effort_controllers/JointPositionController
#   joint: panda_joint6
#   pid: {p: 100.0, i: 0.01, d: 10.0}

# joint7_position_controller:
#   type: effort_controllers/JointPositionController
#   joint: panda_joint7
#   pid: {p: 100.0, i: 0.01, d: 10.0}

# finger1_position_controller:
#   type: effort_controllers/JointPositionController
#   joint: panda_finger_joint1
#   pid: {p: 100.0, i: 0.01, d: 10.0}

# finger2_position_controller:
#   type: effort_controllers/JointPositionController
#   joint: panda_finger_joint2
#   pid: {p: 100.0, i: 0.01, d: 10.0}
